### ISSUE TITLE
gff2json.py doesn't currently accept lists for protein_alias

### ISSUE THREAD

**Issue by miseminger** [cidgoh/nf-ncov-voc#181]
**Issue:**

`gff2json.py` needs adjusting to allow use of new `nf-ncov-voc/assets/virus_genomeAnnotation/NC_045512.2/NC_045512.2_key.json` with aliases written as lists.

**Command:**

`python gff2json.py --gff_file ~/Desktop/git_temp/nf-ncov-voc/assets/virus_genomeAnnotation/NC_045512.2/NC_045512.2.gff --json_file ../assets/virus_geneCoordinates/NC_045512.2/NC_045512.2_with_aliases.json --alias_file ~/Desktop/git_temp/nf-ncov-voc/assets/virus_genomeAnnotation/NC_045512.2/NC_045512.2_key.json
`

**Error:**

```
Traceback (most recent call last):
  File "gff2json.py", line 201, in <module>
    gff_to_json(gff_file_path, json_file_path, gene_colors, alias_dic)
  File "gff2json.py", line 127, in gff_to_json
    features[feature_dict["protein_alias"]] = feature_dict
TypeError: unhashable type: 'list'

```

**Comment by miseminger** [comment]
note: new aliases key is in madeline-1 branch, will be included in pull request
